config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  authenticate :user, lambda { |u| u.admin? } do
    root to: 'admin/tests#index', as: :admin_root
  end

  get 'feedback', to: 'feedback#show', as: :feedback_form
  post 'feedback', to: 'feedback#feedback'

  get '/profile/:id', to: 'profile#show', as: :profile
  patch '/profile/:id', to: 'profile#update', as: :profile_update

  devise_for :users, path: 'guru', path_names: { sign_in: :login, sign_out: :logout }, controllers: { sessions: "users/sessions" }
  resources :tests, only: :index do
    post 'start', on: :member
  end

  resources :test_passing, only: %i[show update] do
    get 'result', on: :member
    post 'save', on: :member
  end

  namespace :admin do
    resources :badges
    get 'gists', to: 'gists#index'
    delete 'gists', to: 'gists#clear_gists'
    resources :tests do
      patch 'update_short', on: :member

      resources :questions, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :users, through: :user_badges
  has_and_belongs_to_many :test_passings

  validates :condition, inclusion: { in: %w[category first_time level],
                                     message: ' value should be only: category, first_time, level.' }
  validates :title, presence: true
  validates :picture_path, presence: true
  validates_with BadgeValidator

  scope :all_activated, -> { where(activated: true) }
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < ApplicationController

  before_action :set_badge, only: %i[show edit update]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def show; end

  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge)
    else
      render :new
    end
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badge_path(@badge)
    else
      flash.alert = t('.cannot_save_badge')
      render :new
    end
  end

  private

  def badge_params
    params.require(:badge).permit(Badge.attribute_names + Badge.reflect_on_all_associations.map { |sym| sym.name.to_s })
  end

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def find_image
    @image = Image.find(params[:image_id])
  end
end

app/helpers/admin/badges_helper.rb
module Admin::BadgesHelper
  def condition_view(badge)
    "#{badge.condition} : #{badge.value} " 
  end
end

app/views/admin/badges/_form.html.erb
<div class="row">
  <%= form_with model:[:admin, @badge] do |form| %>
    <p>
      <%= form.label t('.title') %>
      <%= form.text_field :title, class: "form-control not_empty" %>
    </p>
    <p>
      <%= form.label :image %>
      <%= form.text_field :picture_path, class: "form-control not_empty"  %>
    </p> 
    <p>
      <%= form.label t('.condition') %>
      <%= form.select :condition, [['Category', 'category'], ['First_time', 'first_time'], ['Level', 'level']], {class: "form-select"}  %>
    </p>
    <p>
      <%= form.label t('.value') %>
      <%= form.text_field :value, class: "form-control not_empty" %>
    </p>
          <%= form.label t('.activated') %>
      <%= form.select :activated, [['activated', true], ['diactivated', false]], {class: "form-select"}  %>
    <br>
    <div class="actions">
      <%= form.submit t('.create'), class: "btn btn-light" %>
    </div>
  <% end %>
</div>

app/views/admin/badges/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', badge: @badge%>

<%= link_to t('show'), admin_badge_path(@badge), class: "link-secondary" %> |
<%= link_to t('back'), admin_badge_path, class: "link-secondary" %>

app/views/admin/badges/index.html.erb
<h1><%= t('.badges') %> </h1>

<p><%= link_to t('.new_badge'), new_admin_badge_path, class: "link-secondary" %></p>

<table class="table table-borderless">

  <tr>
    <th> <%= t('.title') %> </th>
    <th> <%= t('.picture') %> </th>
    <th> <%= t('.condition') %> </th>
  </tr>

  <% @badges.each do |badge|%>
    <tr class="col-12 col-md-4 content">
      <td  vertical-align="middle">
        <%= content_tag :span, badge.title, class: 'badge-title' %>  
      </td>
      <td>
        <%= content_tag :span, badge&.picture_path , class: 'badge-title' unless badge.picture_path.nil? %>  
      </td>
      <td>
        <%= content_tag :span, condition_view(badge), class: 'badge-title' %>  
      </td>
      <td>
        <%= link_to t('show'), admin_badge_path(badge), class: "btn btn-light" %>
      </td>
      <td>
        <%= link_to t('update'), edit_admin_badge_path(badge), class: "btn btn-light" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/badges/new.html.erb
<h1><%= t('.title') %></h1>

<%= link_to t('back'), admin_badges_path, class: "link-secondary" %>

<%= render 'form', badge: @badge %>

app/views/admin/badges/show.html.erb
<div>
  <h1><%= t('.title', badge: @badge.title) %></h1>

  <p><%= link_to t('.all_badges'), admin_badges_path, class: "link-secondary" %></p>

  <p><%= link_to t('.edit'), edit_admin_badge_path(@badge), class: "link-secondary" %></p>

  <img src= <%= path_to_image @badge.picture_path unless @badge.picture_path.nil?  %> alt= "<%= @badge.title  %>" >

  <table class="table table-borderless">
    <thead>
      <tr class="col-12 col-md-4 content">
        <th><%= t('.condition') %></th>
        <th><%= t('.activated') %></th>
      </tr>
    </thead>
    <td><%= condition_view(@badge) %> </td>
    <td><%= @badge.activated %> </td>
  </table>
</div>