config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  authenticate :user, lambda { |u| u.admin? } do
    root to: 'admin/tests#index', as: :admin_root
  end

  get 'feedback', to: 'feedback#show', as: :feedback_form
  post 'feedback', to: 'feedback#feedback'

  get '/profile/:id', to: 'profile#show', as: :profile
  patch '/profile/:id', to: 'profile#update', as: :profile_update

  devise_for :users, path: 'guru', path_names: { sign_in: :login, sign_out: :logout }, controllers: { sessions: "users/sessions" }
  resources :tests, only: :index do
    post 'start', on: :member
  end

  resources :test_passing, only: %i[show update] do
    get 'result', on: :member
    post 'save', on: :member
  end

  namespace :admin do
    resources :badges
    get 'gists', to: 'gists#index'
    delete 'gists', to: 'gists#clear_gists'
    resources :tests do
      patch 'update_short', on: :member

      resources :questions, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :test_passings
  has_many :gists
  belongs_to :test

  validates :body, presence: true

  def self.answers?(questions)
    return false if questions.empty?

    questions.each do |question|
      return false if question.answers.empty?
    end
    true
  end

  def fullfilled?
    answers.present?
  end
end

app/models/test_passing.rb
class TestPassing < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  has_and_belongs_to_many :badges

  before_create :before_save_set_first_question
  before_update :before_update_next_question

  SUCCESS_LEVEL = 85

  def completed?
    return true if current_question.nil?

    false
  end

  def issue_badge
    BadgeFinder.new(self).find_badge
  end

  def tag_successfull
    self.successfull = true if successfull?
    save!
  end

  def mark
    (correct_questions.to_f / total_questions) * 100
  end

  def progress
    ((current_question_number.to_f / total_questions) * 100).to_i
  end

  def current_question_number
    total_questions - self.test.questions.order(:id).where('id > ?', current_question.id).count
  end

  def total_questions
    test.questions.count
  end

  def successfull?
    mark >= SUCCESS_LEVEL
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if check_answers?(answer_ids)
    save!
  end

  def minutes_left
    created_at + self.test.time_limit.minutes - Time.now
  end

  def deadline
    created_at + self.test.time_limit.minutes
  end

  def time_left?
    minutes_left.negative?
  end

  private

  def before_save_set_first_question
    self.current_question = test.questions.first if test.questions.first.present?
  end

  def check_answers?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct_answers if current_question.present?
  end

  def before_update_next_question
    return if completed?

    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passing_controller.rb
class TestPassingController < ApplicationController
  before_action :find_test_passing, only: %i[show update result save]
  before_action :check_time_limit, only: %i[show update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_test_passing_not_found

  rescue_from ActionController::ParameterMissing, with: :rescue_no_answers_sent

  def show; end

  def result; end

  def update
    @test_passing.accept!(test_params)
    if @test_passing.completed?
      @test_passing.tag_successfull
      @test_passing.issue_badge if @test_passing.successfull
      redirect_to result_test_passing_path(@test_passing)
    else
      render :show
    end
  end

  def save
    gist_service = GistSaveService.new
    @gist = Gist.new(
      user_id: current_user.id,
      question_id: @test_passing.current_question.id,
      link: gist_service.call(@test_passing)
    )

    redirect_to @test_passing, flash_message(gist_service.success? & @gist.save)
  end

  private

  def rescue_no_answers_sent
    flash.now[:alert] = t('.no_answers')
    render :show
  end

  def flash_message(saved_success)
    if saved_success
      { notice: "#{t('.gist_saved')} #{view_context.link_to 'link', @gist&.link}" }
    else
      { alert: t('.gist_not_saved') }
    end
  end

  def rescue_test_passing_not_found
    redirect_to root_path, alert: t('.no_test_passing')
  end

  def find_test_passing
    @test_passing = TestPassing.find(params[:id])
  end

  def test_params
    params.require(:answer_ids)
  end

  def check_time_limit
    redirect_to result_test_passing_path(@test_passing) if @test_passing.time_left?
  end
end

app/helpers/test_passing_helper.rb
module TestPassingHelper
  def result_final_text(test_passing)
    if test_passing.successfull?
      { color: 'green', text: t('test_passing.result.success') }
    else
      { color: 'red', text: t('test_passing.result.bad_result') }
    end
  end

  def earned_badge(test_passing)
    return if test_passing.badges.empty?

    test_passing.badges.map do |badge|
      "<td  vertical-align='middle'>#{content_tag :span, badge.title, class: 'badge-title'}</td>
      <td>#{image_tag badge.picture_path, alt: badge.title, size: 150}</td>"
    end.unshift("<h3> #{t('earned_badges')} </h3>").join(' ').html_safe
  end
end

app/views/test_passing/result.html.erb
<p> <%= link_to t('.all_tests'), tests_path %></p>
<% test_result = result_final_text(@test_passing) %>
<p><font size='6' color= <%= test_result[:color]%> face='serif'><%= test_result[:text] %></font></p>
<p><font size='6' color= <%= test_result[:color]%> face='serif'> <%= t('.mark') %> <%= @test_passing.mark %></font></p>
<p> <%= earned_badge(@test_passing) %><p>

app/views/test_passing/show.html.erb
<h1> <%= t('.title') %> <%= @test_passing.test.title %> </h1>

<%= content_tag(:span, @test_passing.deadline ,id: 'time_left', data: { result: result_test_passing_path(@test_passing) }) %>

<div class="timer" id="clockdiv">
  <div class="float_left" >
    <span class="minutes tablecell"></span>
    <div class="smalltext tablecell"><%= t("minutes") %></div>
  </div>
  <div class="float_right">
    <span class="seconds tablecell"></span>
    <div class="smalltext tablecell"><%= t("seconds") %></div>
  </div>
</div>

<div id="Progress">
  <%= content_tag(:div,"#{@test_passing.progress} %", id: 'Bar', data: {progress: @test_passing.progress}) %>
</div>

<p><%= link_to t('.save_gist'), save_test_passing_path(@test_passing.id),  method: :post%></p>

<%= @test_passing.current_question.body %>
<%= form_with url: test_passing_path(@test_passing), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passing.current_question.answers, :id, :value, include_hidden: false do |b| %>
    <p> 
      <%= b.check_box id: "answer_ids_#(b.object.id)"%>
      <%= b.label %>
    </p>
  <% end %>
  <%= form.submit t('.submit'), class: "btn btn-light" %>
<% end %>