config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  authenticate :user, lambda { |u| u.admin? } do
    root to: 'admin/tests#index', as: :admin_root
  end

  get 'feedback', to: 'feedback#show', as: :feedback_form
  post 'feedback', to: 'feedback#feedback'

  get '/profile/:id', to: 'profile#show', as: :profile
  patch '/profile/:id', to: 'profile#update', as: :profile_update

  devise_for :users, path: 'guru', path_names: { sign_in: :login, sign_out: :logout }, controllers: { sessions: "users/sessions" }
  resources :tests, only: :index do
    post 'start', on: :member
  end

  resources :test_passing, only: %i[show update] do
    get 'result', on: :member
    post 'save', on: :member
  end

  namespace :admin do
    resources :badges
    get 'gists', to: 'gists#index'
    delete 'gists', to: 'gists#clear_gists'
    resources :tests do
      patch 'update_short', on: :member

      resources :questions, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :test_passings
  has_many :gists
  belongs_to :test

  validates :body, presence: true

  def self.answers?(questions)
    return false if questions.empty?

    questions.each do |question|
      return false if question.answers.empty?
    end
    true
  end

  def fullfilled?
    answers.present?
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :find_test, only: %i[index new create]
  before_action :find_question, except: %i[index new create]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_question_not_found

  def index
    @questions = @test.questions
  end

  def show
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_question_path(@question)
    else
      flash.alert = t('Cannot_save_badge')
      render :new
    end
  end

  def destroy
    @question.destroy
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def rescue_question_not_found
    redirect_to root_path, alert: t('.no_question')
  end

  def question_params
    params.require(:question).permit(:body)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/admin/questions/_form.html.erb
<p><%= question_header(@question) %></p>

<%= form_for([:admin, @test, @question]) do |form|%>
  <p>
    <%= form.label :body %>
    <%= form.text_field :body %>
  </p>
  <br>
  <p>
    <%= form.submit %>
  </p> 
<% end %>

app/views/admin/questions/_question.html.erb
      <tr>
        <td><%= question.body %></td>
        <td><%= link_to t('show'), admin_question_path(question), class: "btn btn-light" %></td>
        <td><%= link_to t('edit'), edit_admin_question_path(question), class: "btn btn-light"  %></td>
        <td><%= link_to t('destroy'), admin_question_path(question), method: :delete, confirm: t('are_you_sure'), class: "btn btn-light" %></td>
      </tr>

app/views/admin/questions/destroy.html.erb
<h1>Question has been succefully deleted.</h1>


<p>Question <%= @question.id %> with body: <%= @question.body %> has been deleted</p>

<p> <%= link_to @question.test.title, admin_test_path(@question.test) %></p>

app/views/admin/questions/edit.html.erb
<%= render 'form' %>

app/views/admin/questions/index.html.erb
<h1>Test <%= @test.title %> all questions </h1>

<p><%= link_to 'New Question', new_admin_test_question_path %> </p>
<p> <%= link_to 'All_tests', admin_tests_path %></p>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <%= render @questions %>
</table>

app/views/admin/questions/new.html.erb
<%= render 'form' %>
    

app/views/admin/questions/show.html.erb
<h1><%= t('.title') %> <%= params[:id] %> </h1>

<p> <%= link_to @question.test.title, admin_test_path(@question.test) %></p>

<p>
  <label for='question-body'><%= t('.body') %></label>
  <p><%= @question.body %></p>
  <p><%= link_to t('destroy'), admin_question_path(@question), :method => :delete %> </p>
  <p><%= link_to t('edit'), edit_admin_question_path(@question) %> </p>
  <label for='question-answers'> <%= t('.answers') %></label>
  <p><%= link_to t('.new_answer'), new_admin_question_answer_path(@question) %> </p>
  <table>
    <thead>
      <tr>
        <th><%= t('.answer') %></th>
        <th><%= t('.correct') %></th>
      </tr>
    </thead>
    <tbody>
    <%= render @question.answers%>
    </tbody>
  </table>
</p>