config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  authenticate :user, lambda { |u| u.admin? } do
    root to: 'admin/tests#index', as: :admin_root
  end

  get 'feedback', to: 'feedback#show', as: :feedback_form
  post 'feedback', to: 'feedback#feedback'

  get '/profile/:id', to: 'profile#show', as: :profile
  patch '/profile/:id', to: 'profile#update', as: :profile_update

  devise_for :users, path: 'guru', path_names: { sign_in: :login, sign_out: :logout }, controllers: { sessions: "users/sessions" }
  resources :tests, only: :index do
    post 'start', on: :member
  end

  resources :test_passing, only: %i[show update] do
    get 'result', on: :member
    post 'save', on: :member
  end

  namespace :admin do
    resources :badges
    get 'gists', to: 'gists#index'
    delete 'gists', to: 'gists#clear_gists'
    resources :tests do
      patch 'update_short', on: :member

      resources :questions, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
  end
end

app/models/achived_badge.rb
class AchivedBadge < ApplicationRecord
  belongs_to :user
end

app/models/admin.rb
class Admin < User
  has_many :created_tests, class_name: :Test, foreign_key: :author_id
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct_answers, -> { where(correct: true) }

  validate :validate_number_answers_in_question

  def validate_number_answers_in_question
    errors.add(:question_id, 'Question has too many answers') if question.answers.length > 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :users, through: :user_badges
  has_and_belongs_to_many :test_passings

  validates :condition, inclusion: { in: %w[category first_time level],
                                     message: ' value should be only: category, first_time, level.' }
  validates :title, presence: true
  validates :picture_path, presence: true
  validates_with BadgeValidator

  scope :all_activated, -> { where(activated: true) }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests
  has_and_belongs_to_many :badges, dependent: :destroy

  default_scope { order(title: :desc) }
end

app/models/gist.rb
class Gist < ApplicationRecord

  belongs_to :question
  belongs_to :user

  validates_format_of :link, with: /gist.github.com/
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :test_passings
  has_many :gists
  belongs_to :test

  validates :body, presence: true

  def self.answers?(questions)
    return false if questions.empty?

    questions.each do |question|
      return false if question.answers.empty?
    end
    true
  end

  def fullfilled?
    answers.present?
  end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :test_passing, dependent: :delete_all
  has_many :users, through: :test_passing
  belongs_to :author, class_name: 'User'
  has_many :questions, dependent: :destroy

  scope :by_level, ->(lev) { where(level: lev) }
  scope :easy, -> { by_level(0..1) }
  scope :moderate, -> { by_level(2..4) }
  scope :advance, -> { by_level(4..Float::INFINITY) }
  scope :find_by_category, ->(category) { Test.joins(:category).where('categories.title = ?', category) }
  scope :for_users, -> { where(published: true) }

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { other_than: 0 }
  validates :time_limit, presence: true
  validate :published, :check_question

  def self.find_order_by_category(category)
    Test.find_by_category(category).order('tests.title DESC').pluck(:title)
  end

  def check_question
    if published && !fullfilled?

      errors.add :fullfilled, :no_question_answers, message: I18n.t('.cannot_publish_no_question_or_answer')
      return false
    end
    true
  end

  def fullfilled?
    return false unless questions.present?

    return false unless Question.answers?(questions)

    true
  end
end

app/models/test_passing.rb
class TestPassing < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  has_and_belongs_to_many :badges

  before_create :before_save_set_first_question
  before_update :before_update_next_question

  SUCCESS_LEVEL = 85

  def completed?
    return true if current_question.nil?

    false
  end

  def issue_badge
    BadgeFinder.new(self).find_badge
  end

  def tag_successfull
    self.successfull = true if successfull?
    save!
  end

  def mark
    (correct_questions.to_f / total_questions) * 100
  end

  def progress
    ((current_question_number.to_f / total_questions) * 100).to_i
  end

  def current_question_number
    total_questions - self.test.questions.order(:id).where('id > ?', current_question.id).count
  end

  def total_questions
    test.questions.count
  end

  def successfull?
    mark >= SUCCESS_LEVEL
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if check_answers?(answer_ids)
    save!
  end

  def minutes_left
    created_at + self.test.time_limit.minutes - Time.now
  end

  def deadline
    created_at + self.test.time_limit.minutes
  end

  def time_left?
    minutes_left.negative?
  end

  private

  def before_save_set_first_question
    self.current_question = test.questions.first if test.questions.first.present?
  end

  def check_answers?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct_answers if current_question.present?
  end

  def before_update_next_question
    return if completed?

    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord 

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable

  has_many :test_passings
  has_many :tests, through: :test_passings
  has_many :gists
  has_many :badges, through: :test_passings

  def create
    self.type = 'User'
  end

  def history(level)
    Test.joins(:users).where('tests.level = ? AND user_id = ?', level, id)
  end

  def admin?
    is_a?(Admin)
  end

  def full_name
    first_name + last_name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_name
    if user_signed_in?
      link_to " #{t('menu.welcome')}, #{current_user.login} #{t('menu.guru')} ", profile_path(current_user)
    else
      link_to t('menu.register'), new_user_registration_path
    end
  end

  def log_in_out
    if user_signed_in?
      link_to(t('menu.logout'), destroy_user_session_path, method: :delete, class: 'link-secondary')
    else
      link_to(t('menu.login'), new_user_session_path)
    end
  end

  def flash_message_class(level)
    classes = {
      notice: 'alert alert-info',
      success: 'alert alert-success',
      error: 'alert alert-danger',
      alert: 'alert alert-warning'
    }

    classes[level.to_sym]
  end
end

app/helpers/current_year_helper.rb
module CurrentYearHelper
  def current_year
    Time.now.year
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/github_url_helper.rb
module GithubUrlHelper
  def github_url(author)
    appname = Rails.application.class.module_parent.name
    link_to appname, "https://github.com/#{author}/#{appname.downcase}/"
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
  include Admin::BadgesHelper

  def user_condition_view(badge)
    condition_view(badge)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_pack_tag 'application', media: 'all' %>
    </head>

    <%= render 'shared/nav' %>

    <%= render 'shared/errors'%>


    <body>
      <div class="container">
        <%= yield %>
      </div>

        <script>
          var language = "<%= I18n.locale %>";
          I18n.translations = <%== I18n::JS.filtered_translations.to_json %>;
        </script>
    </body>
    <br>
    <footer>
      <div class="container">
        <p>
          <p><%= link_to t('feedback_link'), feedback_form_path %></p>
          <p><%= t('footer.part1') %> </p>
          <p><%= t('footer.part2', github: github_url('fingersi')).html_safe  %>
          <p><%= t('footer.part3', href: (link_to 'Thinknetica', "https://thinknetica.com/")).html_safe %> </p>
          <p>Copyright <%= current_year %></p>
        </p>
      </div>
    <footer>
</html>

app/views/shared/_errors.html.erb
<% if flash.present? %>
  <% flash.each do |error| %>  
    <%= content_tag :p, "#{error[0]}: #{error[1]}", class: flash_message_class(error[0]) %>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark flex-sm-nowrap flex-wrap">
  <div class="container">
    <a class="navbar-brand" href= <%= root_path %>>Testguru</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
        <% if current_user&.admin? %> 
          <li class="nav-item active">
              <a class="nav-link" href= <%=admin_tests_path%>><span class="sr-only">Admin panel</span></a> 
          </li>
          <li>
            <a class="nav-link" href= <%=admin_badges_path%>><span class="sr-only">Badges</span></a> 
          </li>
        <% end %>
        </ul>
      </div>
      <span class="navbar-text">
        <b> <%= user_name %> | <%= log_in_out %> </b>
      </span>
    </div>
</nav>